# Generated by Django 3.2.12 on 2023-05-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='links',
        ),
    ]
