# Generated by Django 3.2.12 on 2023-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_serv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pno', models.CharField(max_length=50)),
                ('sdate', models.DateField(max_length=50)),
                ('fdate', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('no_child', models.IntegerField()),
                ('no_adults', models.IntegerField()),
            ],
        ),
    ]
