# Generated by Django 3.2.12 on 2023-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('links', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=300)),
            ],
        ),
    ]
