# Generated by Django 3.2.12 on 2023-05-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20230523_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
