# Generated by Django 3.2.12 on 2023-05-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
