# Generated by Django 3.2.12 on 2023-05-25 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_alter_video_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='links',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
