# Generated by Django 3.2.12 on 2023-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_kdhl001_kdhl002_kdhl003_kdhl004_kdhl005_kdhl006_kdhl007_kdhl008_kdhl009_kdhl010_kdhl011_kdhl012'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDHC001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC007',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC008',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KDHC009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
    ]
