# Generated by Django 3.2.12 on 2023-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0031_kdhc001_kdhc002_kdhc003_kdhc004_kdhc005_kdhc006_kdhc007_kdhc008_kdhc009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day007',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day008',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day012',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day013',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
    ]
