# Generated by Django 3.2.12 on 2023-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0034_poster001_poster002_poster003_poster004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
    ]
